version: '3.8'
services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_NAME=task_management
  #     - DB_USER=postgres
  #     - DB_PASSWORD=postgres
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - KEYCLOAK_URL=http://keycloak:8080
  #     - KEYCLOAK_REALM=task-management
  #     - KEYCLOAK_CLIENT_ID=task-api
  #     - KEYCLOAK_CLIENT_SECRET=your_client_secret
  #     - SESSION_SECRET=your_session_secret
  #     - PORT=3000
  #   depends_on:
  #     - postgres
  #     - redis
  #     - keycloak

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=task_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: start-dev