openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
paths:
  /tasks:
    post:
      summary: Create a task
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title: { type: string }
                description: { type: string }
                status: { type: string, enum: [pending, in_progress, completed] }
                notes: { type: string }
      responses:
        '201': { description: Task created }
    get:
      summary: Get all tasks
      security:
        - bearerAuth: []
      responses:
        '200': { description: List of tasks }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT